const initialData = [
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
  {
    fullname: 'Peregrin Tuk',
    city: 'London',
    country: 'United Kingdom',
    phone: '123456789',
    email: 'pippin@lotr.com',
    skills: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    fullname: 'Meriadoc Brandigamo',
    city: 'Barcelona',
    country: 'Spain',
    phone: '123456789',
    email: 'merry@lotr.com',
    skills: ['NodeJS', 'TypeScript'],
  },
];

const fillTable = (data = initialData) => {
  const table = document.getElementById('table');

  for (const item of data) {
    const tr = table.insertRow(-1);
    for (const prop in item) {
      const td = document.createElement('td');
      if (prop !== 'skills') {
        td.innerHTML = item[prop];
      } else {
        const div = document.createElement('div');
        div.classList.add('skill-container');
        for (let i = 0; i < 2; i++) {
          const p = document.createElement('p');
          p.classList.add('skill-tag');
          p.innerHTML = item[prop][i];
          div.appendChild(p);
        }
        if (item[prop].length > 2) {
          const p = document.createElement('p');
          p.classList.add('skill-tag');
          p.innerHTML = `+${item[prop].length - 2}`;
          div.appendChild(p);
        }
        td.appendChild(div);
      }

      tr.appendChild(td);
    }
  }
};

fillTable();
